{% set name = "scorec" %}
{% set version = "2.2.1.63.g2cdb8ef" %}
{% set build = 0 %}
{% set sha256 = "e6a942d21c067e4242a5dd4267749e8f72d31a2dede245cc0ca8b5f223015c88" %}

{% set mpi = mpi or 'mpich' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #fn: SCOREC-core-2.2.1-63-g2cdb8ef.tar.gz
  url: https://github.com/SCOREC/core/archive/2.2.1-63-g2cdb8ef.tar.gz
  sha256: {{ sha256 }}
#  patches:
#    - 0001-fix-malloc-usage.patch  # [osx]
#    - 0002-fmemopen-memstream-ports-for-darwin.patch  # [osx]

build:
  number: {{ build }}
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - {{ mpi }}
    - metis 5.1
    - parmetis 4.0
    - zoltan 3

test:
  commands:
    - test -f ${PREFIX}/include/zoltan.h  # [unix]

about:
  home: https://www.scorec.rpi.edu/software.php
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The SCOREC Core is a set of C/C++ libraries for unstructured mesh simulations on supercomputers.

extra:
  recipe-maintainers:
    - davidbrochart
    - SylvainCorlay
